import {useState} from 'react'
import {Link} from 'react-router-dom'
import {products,COLLECTIONS,HEX,inr,saveProduct,deleteProduct,resetCatalog,useCatalog,setSiteImage,siteImg} from '../data/products'
import {useOrders,updateOrder,deleteOrder} from '../data/orders'
import {ADMIN_PASSWORD,SHOP} from '../config/shop'
import {Img,Field,WhatsApp,btnP,btnO} from '../components/ui'
import {sendOrderNotification} from '../data/email'
import AdminReviews from './AdminReviews'
import AdminSales from './AdminSales'
import {salesMetrics} from '../data/sales'
const sel='min-h-11 w-full border border-gold-dark/50 bg-white px-3'
const toData=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const i=new Image();i.onload=()=>{const s=Math.min(1,800/i.width),c=document.createElement('canvas');c.width=i.width*s;c.height=i.height*s;c.getContext('2d').drawImage(i,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.75))};i.onerror=rej;i.src=r.result};r.onerror=rej;r.readAsDataURL(f)})
function ImgIn({label,value,onChange}){const [m,setM]=useState(''),up=value?.startsWith('data:'),id='i'+label.replace(/\W/g,'')
 const pick=async e=>{const f=e.target.files?.[0];setM('');if(!f)return;try{onChange(await toData(f));setM('')}catch{setM('Could not read that image.')}}
 return <div className="flex gap-3"><div className="h-28 w-20 shrink-0 overflow-hidden bg-ivory-dark"><Img src={value} alt={label+' preview'} className="h-full w-full object-cover"/></div>
  <div className="flex-1 space-y-1"><Field label={label+' — image URL'} id={id} value={up?'(uploaded photo)':value||''} readOnly={up} onChange={e=>onChange(e.target.value)}/>
   <label className="block text-sm">Or upload: <input type="file" accept="image/*" onChange={pick}/></label>{value&&<button type="button" className="text-sm underline" onClick={()=>{onChange('');setM('')}}>Remove image</button>}{m&&<p role="alert" className="text-sm text-red-700">{m}</p>}</div></div>}
const blank=()=>({id:'kfs-'+Date.now().toString(36),name:'',collection:COLLECTIONS[0],colour:'Maroon',fabric:'',zari:'',price:5000,blouse:'Unstitched blouse piece included (sample detail — confirm in store).',care:'Dry clean only.',stock:true,best:false,isNew:true,images:['','','']})
function Form({init,onDone}){const [p,setP]=useState(init),[err,setErr]=useState(''),set=(k,v)=>setP({...p,[k]:v})
 const submit=e=>{e.preventDefault();if(p.name.trim().length<2)return setErr('Enter a product name.');if(!(+p.price>0))return setErr('Enter a price above 0.')
  if(!saveProduct({...p,price:+p.price,hex:HEX[p.colour]}))return setErr('Browser storage is full. Use smaller photos or paste image URLs.');onDone()}
 const S=({k,l,o})=><div><label htmlFor={k} className="mb-1 block text-sm font-bold">{l}</label><select id={k} className={sel} value={p[k]} onChange={e=>set(k,e.target.value)}>{o.map(x=><option key={x}>{x}</option>)}</select></div>
 return <form onSubmit={submit} noValidate className="space-y-4 border border-gold/50 bg-white p-5"><h2 className="text-2xl">{products.some(x=>x.id===p.id)?'Edit product':'Add product'}</h2>
  <Field label="Name" id="name" value={p.name} onChange={e=>set('name',e.target.value)}/><div className="grid gap-4 sm:grid-cols-2"><S k="collection" l="Collection" o={COLLECTIONS}/><S k="colour" l="Colour" o={Object.keys(HEX)}/>
  <Field label="Fabric" id="fabric" value={p.fabric} onChange={e=>set('fabric',e.target.value)}/><Field label="Zari details" id="zari" value={p.zari} onChange={e=>set('zari',e.target.value)}/><Field label="Price (₹)" id="price" type="number" min="1" value={p.price} onChange={e=>set('price',e.target.value)}/><Field label="Blouse piece" id="blouse" value={p.blouse} onChange={e=>set('blouse',e.target.value)}/></div>
  <Field area label="Care instructions" id="care" value={p.care} onChange={e=>set('care',e.target.value)}/>
  <div className="flex flex-wrap gap-5">{[['stock','In stock'],['best','Bestseller'],['isNew','New arrival']].map(([k,l])=><label key={k} className="flex min-h-11 items-center gap-2"><input type="checkbox" className="h-5 w-5 accent-maroon" checked={p[k]} onChange={e=>set(k,e.target.checked)}/>{l}</label>)}</div>
  {['Drape photo','Zari close-up','Model photo'].map((l,i)=><ImgIn key={l} label={l} value={p.images[i]} onChange={v=>set('images',p.images.map((x,j)=>j===i?v:x))}/>)}
  {err&&<p role="alert" className="text-red-700">{err}</p>}<div className="flex gap-3"><button className={btnP}>Save product</button><button type="button" className={btnO} onClick={onDone}>Cancel</button></div></form>}
const NAV=[['dash','Dashboard'],['products','Products'],['orders','Orders'],['sales','Sales analytics'],['reviews','Reviews'],['site','Site images']]
const STATUS=['New','Packed','Delivered','Cancelled','Refunded'],PAYMENTS=['unpaid','paid','failed','refunded'],BADGE={New:'bg-gold/30 text-gold-dark',Packed:'bg-blue-100 text-blue-800',Delivered:'bg-emerald/15 text-emerald',Cancelled:'bg-red-100 text-red-800',Refunded:'bg-red-100 text-red-800'}
const lines=o=>(o.items||[]).map(i=>typeof i==='string'?i:`${i.name} × ${i.q}`)
const Stat=({t,v})=><div className="border border-gold/40 bg-white p-4 shadow-sm"><p className="text-sm text-ink/60">{t}</p><p className="mt-1 font-serif text-3xl font-semibold text-maroon">{v}</p></div>
const Badge=({s})=><span className={'rounded-full px-2.5 py-0.5 text-xs font-bold '+(BADGE[s||'New'])}>{s||'New'}</span>
function Orders({orders,limit}){const list=limit?orders.slice(0,limit):orders
 if(!list.length)return <p className="border border-gold/40 bg-white p-8 text-center text-ink/70">No orders yet. Orders placed through the shop checkout appear here instantly.</p>
 const resendEmail=async o=>{updateOrder(o.no,{emailStatus:'sending',emailError:''});try{await sendOrderNotification(o);updateOrder(o.no,{emailStatus:'sent',emailError:''})}catch(error){updateOrder(o.no,{emailStatus:'error',emailError:error instanceof Error?error.message:'Could not send the order email.'})}}
 return <ul className="space-y-4">{list.map(o=><li key={o.no} className="border border-gold/40 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-gold/30 pb-3"><div><p className="font-bold">{o.no} <Badge s={o.status}/></p><p className="mt-1 text-xs text-ink/60">{o.at}</p></div><p className="font-serif text-xl font-semibold text-maroon">{inr(o.total)}</p></div>
  <div className="mt-4 grid gap-5 text-sm sm:grid-cols-2"><section><h3 className="font-bold">Customer & delivery</h3><dl className="mt-2 space-y-1"><div><dt className="inline font-semibold">Name: </dt><dd className="inline">{o.name}</dd></div><div><dt className="inline font-semibold">Phone: </dt><dd className="inline"><a href={'tel:'+o.phone} className="underline">{o.phone}</a></dd></div><div><dt className="inline font-semibold">Email: </dt><dd className="inline"><a href={'mailto:'+o.email} className="break-all underline">{o.email}</a></dd></div><div><dt className="inline font-semibold">Address: </dt><dd className="inline text-ink/70">{o.address}</dd></div></dl></section><section><h3 className="font-bold">Items</h3><ul className="mt-2 list-inside list-disc">{lines(o).map((l,i)=><li key={i}>{l}</li>)}</ul></section></div>
  {!limit&&<div className="mt-4 space-y-3 border-t border-gold/30 pt-3"><div className="flex flex-wrap items-center gap-2 text-sm"><span className="font-bold">Email notification to {SHOP.email}:</span><span role={o.emailStatus==='error'?'alert':'status'}>{o.emailStatus==='sent'?'Sent':o.emailStatus==='sending'?'Sending…':o.emailStatus==='error'?'Failed':'No send record'}</span>{o.emailError&&<span className="text-red-700">{o.emailError}</span>}</div><div className="flex flex-wrap items-center gap-3"><button type="button" className={btnO} disabled={o.emailStatus==='sending'||o.emailStatus==='sent'} onClick={()=>resendEmail(o)}>{o.emailStatus==='sending'?'Sending…':o.emailStatus==='sent'?'Email sent':'Send / retry email'}</button><WhatsApp label="WhatsApp order enquiry" text={`Hello Kandan Family Shop, I am enquiring about order ${o.no}.\nItems: ${lines(o).join(', ')}\nTotal: ${inr(o.total)}`}/><label className="text-sm font-bold" htmlFor={'st'+o.no}>Order status</label><select id={'st'+o.no} className="min-h-11 border border-gold-dark/50 bg-white px-2" value={o.status||'New'} onChange={e=>updateOrder(o.no,{status:e.target.value})}>{STATUS.map(x=><option key={x}>{x}</option>)}</select><label className="text-sm font-bold" htmlFor={'pay'+o.no}>Payment</label><select id={'pay'+o.no} className="min-h-11 border border-gold-dark/50 bg-white px-2" value={o.paymentStatus||'unpaid'} onChange={e=>updateOrder(o.no,{paymentStatus:e.target.value})}>{PAYMENTS.map(x=><option key={x} value={x}>{x}</option>)}</select><button className="ml-auto min-h-11 px-3 text-sm text-red-700 underline" onClick={()=>confirm('Delete order '+o.no+'?')&&deleteOrder(o.no)}>Delete</button></div></div>}</li>)}</ul>}
export default function Admin(){useCatalog();const orders=useOrders(),[ok,setOk]=useState(()=>sessionStorage.getItem('kfs_admin')==='1'),[pw,setPw]=useState(''),[bad,setBad]=useState(false),[tab,setTab]=useState('dash'),[edit,setEdit]=useState(null),[m,setM]=useState(''),[q,setQ]=useState('')
 if(!ok)return <main className="weave grid min-h-screen place-items-center bg-maroon-dark p-4"><div className="w-full max-w-sm border-t-4 border-gold bg-ivory p-8 shadow-xl"><h1 className="text-3xl">Admin login</h1><p className="mt-1 text-sm text-ink/70">Kandan Family Shop · demo. The password is set in src/config/shop.js and is not secure.</p>
  <form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();if(pw===ADMIN_PASSWORD){sessionStorage.setItem('kfs_admin','1');setOk(true)}else setBad(true)}}><Field label="Password" id="pw" type="password" value={pw} onChange={e=>setPw(e.target.value)} error={bad&&'Incorrect password.'}/><button className={btnP+' w-full'}>Log in</button></form></div></main>
 const keys=['hero','banner','about',...COLLECTIONS.map(c=>'c:'+c)],newN=orders.filter(o=>(o.status||'New')==='New').length,rev=salesMetrics(orders).revenue
 const shown=products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())),go=k=>{setTab(k);setEdit(null)}
 const nb=k=>`flex min-h-11 items-center justify-between gap-2 whitespace-nowrap px-3 text-left text-sm font-bold ${tab===k?'bg-ivory text-maroon':'text-ivory/90 hover:bg-white/10'}`
 return <div className="min-h-screen bg-ivory-dark/60 md:flex"><aside className="weave bg-maroon-dark text-ivory md:sticky md:top-0 md:flex md:h-screen md:w-60 md:shrink-0 md:flex-col"><div className="p-4 md:p-6"><p className="font-serif text-xl">Kandan Family Shop</p><p className="text-xs text-gold">Admin panel · demo</p></div>
  <nav aria-label="Admin" className="flex gap-1 overflow-x-auto px-2 pb-3 md:flex-1 md:flex-col md:overflow-visible md:px-3">{NAV.map(([k,l])=><button key={k} onClick={()=>go(k)} aria-current={tab===k} className={nb(k)}>{l}{k==='orders'&&newN>0&&<span className="rounded-full bg-gold px-2 text-xs text-ink">{newN}</span>}</button>)}
   <Link to="/" className={nb('')+' md:mt-auto'}>View shop</Link><button className={nb('')} onClick={()=>{sessionStorage.removeItem('kfs_admin');setOk(false)}}>Log out</button></nav></aside>
  <main className="min-w-0 flex-1 p-4 sm:p-8"><div className="mb-4 bg-gold/20 p-3 text-xs"><p>Catalog and orders are demo browser data; customer reviews use server-side SQLite storage.</p></div>
  {tab==='dash'&&<><h1 className="text-3xl">Dashboard</h1><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-5"><Stat t="Products" v={products.length}/><Stat t="In stock" v={products.filter(p=>p.stock).length}/><Stat t="Out of stock" v={products.filter(p=>!p.stock).length}/><Stat t="Orders" v={orders.length}/><Stat t="Paid revenue" v={inr(rev)}/></div>
   <h2 className="mb-3 mt-8 text-2xl">Recent orders</h2><Orders orders={orders} limit={5}/>
   <h2 className="mb-3 mt-8 text-2xl">Products by collection</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{COLLECTIONS.map(c=><Stat key={c} t={c} v={products.filter(p=>p.collection===c).length}/>)}</div></>}
  {tab==='products'&&(edit?<Form key={edit.id} init={edit} onDone={()=>setEdit(null)}/>:<><div className="flex flex-wrap items-end justify-between gap-3"><h1 className="text-3xl">Products</h1><div className="flex flex-wrap gap-3"><button className={btnP} onClick={()=>setEdit(blank())}>Add product</button><button className={btnO} onClick={()=>confirm('Reset products and site images to the sample data?')&&resetCatalog()}>Reset sample data</button></div></div>
   <label className="sr-only" htmlFor="pq">Search products</label><input id="pq" type="search" placeholder="Search products" value={q} onChange={e=>setQ(e.target.value)} className={sel+' mt-4 max-w-sm'}/>
   <div className="mt-4 overflow-x-auto border border-gold/40 bg-white shadow-sm"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-ivory-dark"><tr><th className="p-3">Product</th><th className="p-3">Collection</th><th className="p-3">Price</th><th className="p-3">Stock</th><th className="p-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{shown.map(p=><tr key={p.id} className="border-t border-gold/30"><td className="p-3"><div className="flex items-center gap-3"><div className="h-14 w-11 shrink-0 overflow-hidden bg-ivory-dark"><Img src={p.images[0]} alt="" tone={p.hex} className="h-full w-full object-cover"/></div><span className="font-bold">{p.name}</span></div></td><td className="p-3">{p.collection}</td><td className="p-3">{inr(p.price)}</td>
    <td className="p-3"><button className={'rounded-full px-3 py-1 text-xs font-bold '+(p.stock?'bg-emerald/15 text-emerald':'bg-red-100 text-red-800')} aria-pressed={p.stock} onClick={()=>saveProduct({...p,stock:!p.stock})}>{p.stock?'In stock':'Out of stock'}</button></td>
    <td className="whitespace-nowrap p-3 text-right"><button className="min-h-11 px-3 font-bold text-maroon underline" onClick={()=>setEdit(p)}>Edit</button><button className="min-h-11 px-3 text-red-700 underline" onClick={()=>confirm('Delete '+p.name+'?')&&deleteProduct(p.id)}>Delete</button></td></tr>)}</tbody></table>{!shown.length&&<p className="p-6 text-center">No products match.</p>}</div></>)}
  {tab==='orders'&&<><h1 className="mb-5 text-3xl">Orders</h1><Orders orders={orders}/></>}
  {tab==='sales'&&<AdminSales/>}
  {tab==='reviews'&&<AdminReviews/>}
  {tab==='site'&&<><h1 className="mb-5 text-3xl">Site images</h1><div className="grid gap-4 lg:grid-cols-2">{keys.map(k=><div key={k} className="border border-gold/40 bg-white p-4 shadow-sm"><ImgIn label={k.startsWith('c:')?k.slice(2)+' card':k==='hero'?'Hero background':k==='banner'?'Bridal banner':'About photo'} value={siteImg(k)} onChange={v=>setSiteImage(k,v)||setM('Browser storage is full. Use a smaller photo or an image URL.')}/></div>)}</div>{m&&<p role="alert" className="mt-3 text-red-700">{m}</p>}</>}</main></div>}
